### ISSUE TITLE
Can't get the latest pep-web client version to work locally on my PC...

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#492]
I downloaded the latest client on my PC last night to do testing, and there were some errors during the build process, and it didn't work correctly (comes up with a partial client).

Seems to be missing something:

    Cannot find module 'broccoli-funnel'

I don't know if that's the error, because I'm seeing others, but I tried to install it a few times per the posted build instructions.

Also, another build error, but this might have been true in earlier versions as well which worked

<img width="791" alt="2021-05-04_23h29_20" src="https://user-images.githubusercontent.com/4837554/117140662-a8d44b80-ad7b-11eb-9edd-dce3f00d8e4c.png">

Run-time I kept getting this error (and the display was never complete):

<img width="840" alt="2021-05-04_23h29_59" src="https://user-images.githubusercontent.com/4837554/117140595-91955e00-ad7b-11eb-8991-9a7ec4faeb62.png">

I reverted back to the one which is about a week old and that works.  But at some point in the near future, I'd like to be able to install them again for local testing and tracing of calls.

**Comment by nrshapiro** [comment]
@bakerac4 @adistasio 

As I've told Alan, Items marked as Bugs can be worked on/dealt with even if not marked Beta2

I need to be able to install here locally to do proper testing in terms of client-server interactions.

**Comment by bakerac4** [comment]
@nrshapiro what user were you signed in as?

Can you try clearing all your browser data? It looks like it was not able to find 
```const videos = this.configuration.base.global.cards.topicalVideoPreviews;``` 

your topicalVideoPreviews from the configuration.

**Comment by nrshapiro** [comment]
@bakerac4 - I just did an install of the latest version.   Interesting result...can we try to work this out on zoom?  I need to get it running to debug the author/facet problem, which is still there.

Basically, if I used your .env-development file, it works.

BUILD_VERSION=0.0.0
USER_PREFERENCES_VERSION=0.0.0
ROOT_URL=/
ASSETS_BASE_URL=https://gavant.pep-web.rocks:4200/
API_BASE_URL=https://stage-api.pep-web.rocks
API_NAMESPACE=v2
API_DATA_NAMESPACE=Database
API_ADMIN_NAMESPACE=Admin
API_ERRORS_ENDPOINT=/error-events
AUTH_BASE_URL=https://stage-pads.pep-web.rocks/PEPSecure/api/v1
FEDERATED_LOGIN_URL=https://stage-pads.pep-web.rocks/pepsecure/api/configuration
FASTBOOT_WHITELIST_DOMAIN=^gavant\.pep\-web\.rocks:\d+$
ROBOTS_DIST_PATH=/robots-development.txt
CLIENT_ID=2
COOKIE_DOMAIN=pep-web.rocks
COOKIE_SECURE=1
COOKIE_SAME_SITE=None
GOOGLE_ANALYTICS_ID=UA-183879376-1
GOOGLE_ANALYTICS_ENVIRONMENT=production
REPORTS_API=https://n86ico15a5.execute-api.us-east-1.amazonaws.com/tp66838/

But if I change it thusly:

BUILD_VERSION=0.0.0
USER_PREFERENCES_VERSION=0.0.0
ROOT_URL=/
ASSETS_BASE_URL=https://gavant.pep-web.rocks:4200/
API_BASE_URL=http://development.org:9100
API_NAMESPACE=v2
API_DATA_NAMESPACE=Database
API_ADMIN_NAMESPACE=Admin
API_ERRORS_ENDPOINT=/error-events
AUTH_BASE_URL=https://stage-pads.pep-web.rocks/PEPSecure/api/v1
FEDERATED_LOGIN_URL=https://stage-pads.pep-web.rocks/pepsecure/api/configuration
FASTBOOT_WHITELIST_DOMAIN=^gavant\.pep\-web\.rocks:\d+$
ROBOTS_DIST_PATH=/robots-development.txt
CLIENT_ID=2
COOKIE_DOMAIN=development.org
COOKIE_SECURE=1
COOKIE_SAME_SITE=None
GOOGLE_ANALYTICS_ID=UA-183879376-1
GOOGLE_ANALYTICS_ENVIRONMENT=production
REPORTS_API=https://n86ico15a5.execute-api.us-east-1.amazonaws.com/tp66838/

what I see is:

![image](https://user-images.githubusercontent.com/4837554/119034629-8bf36700-b97c-11eb-9cff-4473a058b49c.png)

and the command window shows me:

DEPRECATION: The <pep@component:link-to::ember434>#active computed property was just overridden. This removes the computed property and replaces it with a plain value, and has been deprecated. If you want this behavior, consider defining a setter which does it manually. [deprecation id: computed-property.override] See https://emberjs.com/deprecations/v3.x#toc_computed-property-override for more details.
DEPRECATION: The <pep@component:link-to::ember437>#active computed property was just overridden. This removes the computed property and replaces it with a plain value, and has been deprecated. If you want this behavior, consider defining a setter which does it manually. [deprecation id: computed-property.override] See https://emberjs.com/deprecations/v3.x#toc_computed-property-override for more details.
TypeError: Cannot read property 'length' of undefined
    at PageSidebarWidgetsTopicalVideoPreview.get videoIndex [as videoIndex] (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\pep\pods\components\page\sidebar\widgets\topical-video-preview\component.js:26:1)
    at PageSidebarWidgetsTopicalVideoPreview.get video [as video] (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\pep\pods\components\page\sidebar\widgets\topical-video-preview\component.js:31:1)
    at PageSidebarWidgetsTopicalVideoPreview.get aspectRatio [as aspectRatio] (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\pep\pods\components\page\sidebar\widgets\topical-video-preview\component.js:37:1)
    at getPossibleMandatoryProxyValue (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\@ember\-internals\metal\index.js:1281:1)
    at _getProp (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\@ember\-internals\metal\index.js:1346:1)
    at get (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\@ember\-internals\metal\index.js:1332:1)
    at combined (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\@glimmer\reference.js:318:1)
    at runInAutotrackingTransaction (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\@glimmer\validator.js:121:1)
    at track (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\@glimmer\validator.js:774:1)
    at PropertyReference.value (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\@glimmer\reference.js:317:1)
    at ConcatReference.compute (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\@glimmer\runtime.js:2258:1)
    at ConcatReference.value (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\@glimmer\reference.js:24:1)
    at Object.APPEND_OPCODES.add [as evaluate] (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\@glimmer\runtime.js:3236:1)
    at AppendOpcodes.evaluate (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\@glimmer\runtime.js:2196:1)
    at LowLevelVM.evaluateSyscall (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\@glimmer\runtime.js:5110:1)
    at LowLevelVM.evaluateInner (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\@glimmer\runtime.js:5066:1)
    at LowLevelVM.evaluateOuter (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\@glimmer\runtime.js:5058:1)
    at JitVM.next (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\@glimmer\runtime.js:6131:1)
    at TemplateIteratorImpl.next (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\@glimmer\runtime.js:6259:1)
    at RootState.render (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\@ember\-internals\glimmer\index.js:8781:1)
    at runInAutotrackingTransaction (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\@glimmer\validator.js:121:1)
    at C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\@ember\-internals\glimmer\index.js:9079:1
    at inTransaction (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\@glimmer\runtime.js:2151:1)
    at InertRenderer._renderRoots (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\@ember\-internals\glimmer\index.js:9053:1)
    at InertRenderer._renderRootsTransaction (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\@ember\-internals\glimmer\index.js:9114:1)
    at InertRenderer._renderRoot (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\@ember\-internals\glimmer\index.js:9040:1)
    at InertRenderer._appendDefinition (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\@ember\-internals\glimmer\index.js:8955:1)
    at InertRenderer.appendOutletView (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\@ember\-internals\glimmer\index.js:8941:1)
    at invokeWithOnError (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\backburner.js:349:1)
    at Queue.flush (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\backburner.js:229:1)
    at DeferredActionQueues.flush (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\backburner.js:426:1)
    at Backburner._end (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\backburner.js:960:1)
    at Backburner._boundAutorunEnd (C:\Users\nrsha\AppData\Local\Temp\broccoli-59204Oq9WS4fuMEHy\out-1150-broccoli_persistent_filter_autoprefixer_filter\assets\backburner.js:629:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by bakerac4** [comment]
@nrshapiro Im sure Alan wont mind scheduling a zoom call for us. But until that point, you should open up your browser console and check the requests tab. If I had to guess your getting a CORS issue and thats why nothing is loading (its failing to make any calls successfully).

**Comment by nrshapiro** [comment]
Wow...another notification I missed (didn't see this till now.  Great email app with some real problems lately.  Just writing this for my own records!
